version: '3.8'
services:
  frontend:
    build:
      context: ..
      dockerfile: fe/Dockerfile
    ports:
      - '5173:4173'
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - .:/app
